### ISSUE TITLE
Add context menu

### ISSUE THREAD

**Issue by doseonfairsutdios** [novemberi/clover#13]
**Is your feature request related to a problem? Please describe.**
Even if I disable the codelens setting, I want to use the meta references feature.

**Describe the solution you'd like**
Add "Peek Meta References" to the Context Menu that appears when you right-click on the code you want to check references for.

**Describe alternatives you've considered**
Selecting "Peek Meta References" has the same function as pressing the meta reference in CodeLens.

**Additional context**
If possible, it would be good to be able to check the meta reference in the side bar, like Find All References in the Context Menu.

If so, it would be nice if "Peek Meta References" and "Find Meta References" were added to the Context Menu.

![context menu](https://github.com/novemberi/clover/assets/74888932/2082d2cd-fb16-4ad3-8727-bf5ed0524a4c)

![find all](https://github.com/novemberi/clover/assets/74888932/83d82fc5-d7f7-4c50-9536-718d9c27bc37)

**Comment by novemberi** [comment]
I think codelens is control by vscode. I will investing other way to support your solution with "Peek Referencfes" things.

**Comment by novemberi** [comment]
![image](https://github.com/novemberi/clover/assets/37071240/6c30e024-7da5-44d0-8ae2-6dcc62850c8a)

I want to set my context menu in Peek, (and rename to Peek Meta References) it's hard right now.
Peek category is control by C# language server I guess.
Instead, I add `Find Meta Reference` high priority on top, and add also vscode command `> Find Meta Reference`.
Maybe will be release on 0.5.1.

**Comment by doseonfairsutdios** [comment]
@novemberi 

Thank you for your quick response. For now, that much is efficient enough. awesome!

**Comment by novemberi** [comment]
#15 is merged in develop, and 0.5.1 version is now released.
